### ISSUE TITLE
HU-001-TA-001 Crear el Html inicial con la estructura basica

### ISSUE THREAD

**Issue by LucasA75** [LucasA75/TuCopete#3]
Crear la estructura basica de la pagina 👍 -> Colores : Blanco, Azul y Celeste

1.  Navbar  con el nombre a la izquierda y a la derecha : 
- Contacto
- Licores
- Donde Comprar
2. Menu de Destacados
Tendra algunas imagenes
3. Descripcion de porque ocupar la pagina
4. Footer

**Comment by abrilonia** [comment]
Crea alguna tarea para hacerla Lucas

**Comment by LucasA75** [comment]
> Crea alguna tarea para hacerla Lucas

Te refieres a hacerla mas especifica ? 😅

**Comment by abrilonia** [comment]
Es que esa te la asignaste a ti, y cada tarea la hará solo una persona. Pon hacer un formulario para equis cosa, por ejemplo. O si podemos hacer una tarea los dos no sé cómo sería, cómo sería el tema de las dos ramas, el pull request y todo eso.
